# Generated by Django 4.0.4 on 2022-06-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecetasColombianas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plato', models.CharField(max_length=30, unique=True)),
                ('tiempo_cocina', models.IntegerField()),
                ('ingredientes', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=30)),
                ('dificultad', models.IntegerField()),
                ('fecha_agregada', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RecetasItalianas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plato', models.CharField(max_length=30, unique=True)),
                ('tiempo_cocina', models.IntegerField()),
                ('ingredientes', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=30)),
                ('dificultad', models.IntegerField()),
                ('fecha_agregada', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RecetasMar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plato', models.CharField(max_length=30, unique=True)),
                ('tiempo_cocina', models.IntegerField()),
                ('ingredientes', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=30)),
                ('dificultad', models.IntegerField()),
                ('fecha_agregada', models.DateField()),
            ],
        ),
    ]
