# Generated by Django 4.0.4 on 2022-06-26 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_recetascolombianas_dificultad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetascolombianas',
            name='tiempo_cocina',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(1440)]),
        ),
        migrations.AlterField(
            model_name='recetasitalianas',
            name='tiempo_cocina',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(1440)]),
        ),
        migrations.AlterField(
            model_name='recetasmar',
            name='tiempo_cocina',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(1440)]),
        ),
    ]
